/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t 
Author: WheelchairDrift (https://sketchfab.com/WheelchairDrift)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-uptempo-sneaker3d-scanned-low-poly-b147852f4b3f481aac7a4686b08cf43c
Title: Nike Air Uptempo Sneaker(3D scanned, low poly)
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Nike_Uptempo_Lowpoly_Material_0: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: any
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/1/scene.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Nike_Uptempo_Lowpoly_Material_0.geometry} material={materials.Material} position={[0, 47.949, -4.74]} rotation={[0.049, 0.532, 0.003]} scale={102.856} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/1/scene.gltf')
